//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Gestión.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BACategorias : DbContext
    {
        public BACategorias()
            : base("name=BACategorias")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VW_ListaCategorias> VW_ListaCategorias { get; set; }
    
        public virtual int SP_InsertarCategorias(string nom_Categoria, string des_Categoria)
        {
            var nom_CategoriaParameter = nom_Categoria != null ?
                new ObjectParameter("Nom_Categoria", nom_Categoria) :
                new ObjectParameter("Nom_Categoria", typeof(string));
    
            var des_CategoriaParameter = des_Categoria != null ?
                new ObjectParameter("Des_Categoria", des_Categoria) :
                new ObjectParameter("Des_Categoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertarCategorias", nom_CategoriaParameter, des_CategoriaParameter);
        }
    
        public virtual int SP_ActualizarCategorias(Nullable<int> idCategoria, string nombre, string descripcion)
        {
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("idCategoria", idCategoria) :
                new ObjectParameter("idCategoria", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarCategorias", idCategoriaParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int SP_EliminarCategorias(Nullable<int> idCategoria)
        {
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("idCategoria", idCategoria) :
                new ObjectParameter("idCategoria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarCategorias", idCategoriaParameter);
        }
    }
}
