//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Gestión.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BAClientesModel : DbContext
    {
        public BAClientesModel()
            : base("name=BAClientesModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VW_ListaTipoClientes> VW_ListaTipoClientes { get; set; }
        public virtual DbSet<VW_ListaCiudades> VW_ListaCiudades { get; set; }
        public virtual DbSet<VW_ListaClientes> VW_ListaClientes { get; set; }
    
        public virtual int EliminarCliente(Nullable<int> id_Cliente)
        {
            var id_ClienteParameter = id_Cliente.HasValue ?
                new ObjectParameter("id_Cliente", id_Cliente) :
                new ObjectParameter("id_Cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarCliente", id_ClienteParameter);
        }
    
        public virtual int SP_ActualizarClientes(Nullable<int> iD_Cliente, Nullable<int> iD_ClienteDetalle, string nom_Empresa, string nom_Proyecto, string rnc_Empresa, string cedula_Cliente, string pri_Nombre, string seg_Nombre, string pri_Apellido, string seg_Apellido, Nullable<int> id_TipoCliente, string tl1_Cliente, Nullable<int> ext_Tl1_Cliente, string tl2_Cliente, string dir_Calle, Nullable<int> dir_Numero, string pun_Referencia, Nullable<int> id_Ciudad, Nullable<int> cod_Postal, string correo_Cliente, string pag_WebCliente, string obs_Cliente)
        {
            var iD_ClienteParameter = iD_Cliente.HasValue ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(int));
    
            var iD_ClienteDetalleParameter = iD_ClienteDetalle.HasValue ?
                new ObjectParameter("ID_ClienteDetalle", iD_ClienteDetalle) :
                new ObjectParameter("ID_ClienteDetalle", typeof(int));
    
            var nom_EmpresaParameter = nom_Empresa != null ?
                new ObjectParameter("Nom_Empresa", nom_Empresa) :
                new ObjectParameter("Nom_Empresa", typeof(string));
    
            var nom_ProyectoParameter = nom_Proyecto != null ?
                new ObjectParameter("Nom_Proyecto", nom_Proyecto) :
                new ObjectParameter("Nom_Proyecto", typeof(string));
    
            var rnc_EmpresaParameter = rnc_Empresa != null ?
                new ObjectParameter("Rnc_Empresa", rnc_Empresa) :
                new ObjectParameter("Rnc_Empresa", typeof(string));
    
            var cedula_ClienteParameter = cedula_Cliente != null ?
                new ObjectParameter("Cedula_Cliente", cedula_Cliente) :
                new ObjectParameter("Cedula_Cliente", typeof(string));
    
            var pri_NombreParameter = pri_Nombre != null ?
                new ObjectParameter("Pri_Nombre", pri_Nombre) :
                new ObjectParameter("Pri_Nombre", typeof(string));
    
            var seg_NombreParameter = seg_Nombre != null ?
                new ObjectParameter("Seg_Nombre", seg_Nombre) :
                new ObjectParameter("Seg_Nombre", typeof(string));
    
            var pri_ApellidoParameter = pri_Apellido != null ?
                new ObjectParameter("Pri_Apellido", pri_Apellido) :
                new ObjectParameter("Pri_Apellido", typeof(string));
    
            var seg_ApellidoParameter = seg_Apellido != null ?
                new ObjectParameter("Seg_Apellido", seg_Apellido) :
                new ObjectParameter("Seg_Apellido", typeof(string));
    
            var id_TipoClienteParameter = id_TipoCliente.HasValue ?
                new ObjectParameter("id_TipoCliente", id_TipoCliente) :
                new ObjectParameter("id_TipoCliente", typeof(int));
    
            var tl1_ClienteParameter = tl1_Cliente != null ?
                new ObjectParameter("Tl1_Cliente", tl1_Cliente) :
                new ObjectParameter("Tl1_Cliente", typeof(string));
    
            var ext_Tl1_ClienteParameter = ext_Tl1_Cliente.HasValue ?
                new ObjectParameter("Ext_Tl1_Cliente", ext_Tl1_Cliente) :
                new ObjectParameter("Ext_Tl1_Cliente", typeof(int));
    
            var tl2_ClienteParameter = tl2_Cliente != null ?
                new ObjectParameter("Tl2_Cliente", tl2_Cliente) :
                new ObjectParameter("Tl2_Cliente", typeof(string));
    
            var dir_CalleParameter = dir_Calle != null ?
                new ObjectParameter("Dir_Calle", dir_Calle) :
                new ObjectParameter("Dir_Calle", typeof(string));
    
            var dir_NumeroParameter = dir_Numero.HasValue ?
                new ObjectParameter("Dir_Numero", dir_Numero) :
                new ObjectParameter("Dir_Numero", typeof(int));
    
            var pun_ReferenciaParameter = pun_Referencia != null ?
                new ObjectParameter("Pun_Referencia", pun_Referencia) :
                new ObjectParameter("Pun_Referencia", typeof(string));
    
            var id_CiudadParameter = id_Ciudad.HasValue ?
                new ObjectParameter("id_Ciudad", id_Ciudad) :
                new ObjectParameter("id_Ciudad", typeof(int));
    
            var cod_PostalParameter = cod_Postal.HasValue ?
                new ObjectParameter("Cod_Postal", cod_Postal) :
                new ObjectParameter("Cod_Postal", typeof(int));
    
            var correo_ClienteParameter = correo_Cliente != null ?
                new ObjectParameter("Correo_Cliente", correo_Cliente) :
                new ObjectParameter("Correo_Cliente", typeof(string));
    
            var pag_WebClienteParameter = pag_WebCliente != null ?
                new ObjectParameter("pag_WebCliente", pag_WebCliente) :
                new ObjectParameter("pag_WebCliente", typeof(string));
    
            var obs_ClienteParameter = obs_Cliente != null ?
                new ObjectParameter("Obs_Cliente", obs_Cliente) :
                new ObjectParameter("Obs_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarClientes", iD_ClienteParameter, iD_ClienteDetalleParameter, nom_EmpresaParameter, nom_ProyectoParameter, rnc_EmpresaParameter, cedula_ClienteParameter, pri_NombreParameter, seg_NombreParameter, pri_ApellidoParameter, seg_ApellidoParameter, id_TipoClienteParameter, tl1_ClienteParameter, ext_Tl1_ClienteParameter, tl2_ClienteParameter, dir_CalleParameter, dir_NumeroParameter, pun_ReferenciaParameter, id_CiudadParameter, cod_PostalParameter, correo_ClienteParameter, pag_WebClienteParameter, obs_ClienteParameter);
        }
    
        public virtual int SP_InsertarClientes(string nom_Empresa, string nom_Proyecto, string rnc_Empresa, string cedula_Cliente, string pri_Nombre, string seg_Nombre, string pri_Apellido, string seg_Apellido, Nullable<int> id_TipoCliente, string tl1_Cliente, Nullable<int> ext_Tl1_Cliente, string tl2_Cliente, string dir_Calle, Nullable<int> dir_Numero, string pun_Referencia, Nullable<int> id_Ciudad, Nullable<int> cod_Postal, string correo_Cliente, string pag_WebCliente, string obs_Cliente)
        {
            var nom_EmpresaParameter = nom_Empresa != null ?
                new ObjectParameter("Nom_Empresa", nom_Empresa) :
                new ObjectParameter("Nom_Empresa", typeof(string));
    
            var nom_ProyectoParameter = nom_Proyecto != null ?
                new ObjectParameter("Nom_Proyecto", nom_Proyecto) :
                new ObjectParameter("Nom_Proyecto", typeof(string));
    
            var rnc_EmpresaParameter = rnc_Empresa != null ?
                new ObjectParameter("Rnc_Empresa", rnc_Empresa) :
                new ObjectParameter("Rnc_Empresa", typeof(string));
    
            var cedula_ClienteParameter = cedula_Cliente != null ?
                new ObjectParameter("Cedula_Cliente", cedula_Cliente) :
                new ObjectParameter("Cedula_Cliente", typeof(string));
    
            var pri_NombreParameter = pri_Nombre != null ?
                new ObjectParameter("Pri_Nombre", pri_Nombre) :
                new ObjectParameter("Pri_Nombre", typeof(string));
    
            var seg_NombreParameter = seg_Nombre != null ?
                new ObjectParameter("Seg_Nombre", seg_Nombre) :
                new ObjectParameter("Seg_Nombre", typeof(string));
    
            var pri_ApellidoParameter = pri_Apellido != null ?
                new ObjectParameter("Pri_Apellido", pri_Apellido) :
                new ObjectParameter("Pri_Apellido", typeof(string));
    
            var seg_ApellidoParameter = seg_Apellido != null ?
                new ObjectParameter("Seg_Apellido", seg_Apellido) :
                new ObjectParameter("Seg_Apellido", typeof(string));
    
            var id_TipoClienteParameter = id_TipoCliente.HasValue ?
                new ObjectParameter("id_TipoCliente", id_TipoCliente) :
                new ObjectParameter("id_TipoCliente", typeof(int));
    
            var tl1_ClienteParameter = tl1_Cliente != null ?
                new ObjectParameter("Tl1_Cliente", tl1_Cliente) :
                new ObjectParameter("Tl1_Cliente", typeof(string));
    
            var ext_Tl1_ClienteParameter = ext_Tl1_Cliente.HasValue ?
                new ObjectParameter("Ext_Tl1_Cliente", ext_Tl1_Cliente) :
                new ObjectParameter("Ext_Tl1_Cliente", typeof(int));
    
            var tl2_ClienteParameter = tl2_Cliente != null ?
                new ObjectParameter("Tl2_Cliente", tl2_Cliente) :
                new ObjectParameter("Tl2_Cliente", typeof(string));
    
            var dir_CalleParameter = dir_Calle != null ?
                new ObjectParameter("Dir_Calle", dir_Calle) :
                new ObjectParameter("Dir_Calle", typeof(string));
    
            var dir_NumeroParameter = dir_Numero.HasValue ?
                new ObjectParameter("Dir_Numero", dir_Numero) :
                new ObjectParameter("Dir_Numero", typeof(int));
    
            var pun_ReferenciaParameter = pun_Referencia != null ?
                new ObjectParameter("Pun_Referencia", pun_Referencia) :
                new ObjectParameter("Pun_Referencia", typeof(string));
    
            var id_CiudadParameter = id_Ciudad.HasValue ?
                new ObjectParameter("id_Ciudad", id_Ciudad) :
                new ObjectParameter("id_Ciudad", typeof(int));
    
            var cod_PostalParameter = cod_Postal.HasValue ?
                new ObjectParameter("Cod_Postal", cod_Postal) :
                new ObjectParameter("Cod_Postal", typeof(int));
    
            var correo_ClienteParameter = correo_Cliente != null ?
                new ObjectParameter("Correo_Cliente", correo_Cliente) :
                new ObjectParameter("Correo_Cliente", typeof(string));
    
            var pag_WebClienteParameter = pag_WebCliente != null ?
                new ObjectParameter("pag_WebCliente", pag_WebCliente) :
                new ObjectParameter("pag_WebCliente", typeof(string));
    
            var obs_ClienteParameter = obs_Cliente != null ?
                new ObjectParameter("Obs_Cliente", obs_Cliente) :
                new ObjectParameter("Obs_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertarClientes", nom_EmpresaParameter, nom_ProyectoParameter, rnc_EmpresaParameter, cedula_ClienteParameter, pri_NombreParameter, seg_NombreParameter, pri_ApellidoParameter, seg_ApellidoParameter, id_TipoClienteParameter, tl1_ClienteParameter, ext_Tl1_ClienteParameter, tl2_ClienteParameter, dir_CalleParameter, dir_NumeroParameter, pun_ReferenciaParameter, id_CiudadParameter, cod_PostalParameter, correo_ClienteParameter, pag_WebClienteParameter, obs_ClienteParameter);
        }
    }
}
