//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Gestión.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BoteAgregadosEntities : DbContext
    {
        public BoteAgregadosEntities()
            : base("name=BoteAgregadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VW_VerUsuarios> VW_VerUsuarios { get; set; }
        public virtual DbSet<VW_VerRolesUsuario> VW_VerRolesUsuario { get; set; }
    
        public virtual int SP_ActualizarAccesoLogin(string nombreUsuario)
        {
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("NombreUsuario", nombreUsuario) :
                new ObjectParameter("NombreUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarAccesoLogin", nombreUsuarioParameter);
        }
    
        public virtual int SP_ActualizarUsuario(Nullable<int> idUsuario, string nombre, Nullable<int> perfil, string email, Nullable<int> estatus)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var perfilParameter = perfil.HasValue ?
                new ObjectParameter("Perfil", perfil) :
                new ObjectParameter("Perfil", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarUsuario", idUsuarioParameter, nombreParameter, perfilParameter, emailParameter, estatusParameter);
        }
    
        public virtual int SP_DesactivarUsuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DesactivarUsuario", idUsuarioParameter);
        }
    
        public virtual int SP_InsertarUsuarios(string nom_Usuario, string clave_Usuario, Nullable<int> id_RolUsuario, Nullable<System.DateTime> ultimo_Acceso, string correo_Usuario)
        {
            var nom_UsuarioParameter = nom_Usuario != null ?
                new ObjectParameter("Nom_Usuario", nom_Usuario) :
                new ObjectParameter("Nom_Usuario", typeof(string));
    
            var clave_UsuarioParameter = clave_Usuario != null ?
                new ObjectParameter("Clave_Usuario", clave_Usuario) :
                new ObjectParameter("Clave_Usuario", typeof(string));
    
            var id_RolUsuarioParameter = id_RolUsuario.HasValue ?
                new ObjectParameter("id_RolUsuario", id_RolUsuario) :
                new ObjectParameter("id_RolUsuario", typeof(int));
    
            var ultimo_AccesoParameter = ultimo_Acceso.HasValue ?
                new ObjectParameter("Ultimo_Acceso", ultimo_Acceso) :
                new ObjectParameter("Ultimo_Acceso", typeof(System.DateTime));
    
            var correo_UsuarioParameter = correo_Usuario != null ?
                new ObjectParameter("Correo_Usuario", correo_Usuario) :
                new ObjectParameter("Correo_Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertarUsuarios", nom_UsuarioParameter, clave_UsuarioParameter, id_RolUsuarioParameter, ultimo_AccesoParameter, correo_UsuarioParameter);
        }
    
        public virtual ObjectResult<SP_ObtenerUsuario_Result> SP_ObtenerUsuario(string nombreUsuario)
        {
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("NombreUsuario", nombreUsuario) :
                new ObjectParameter("NombreUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerUsuario_Result>("SP_ObtenerUsuario", nombreUsuarioParameter);
        }
    
        public virtual int SP_CambiarClaveUsuario(Nullable<int> id_Usuario, string claveAnterior, string claveNueva)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            var claveAnteriorParameter = claveAnterior != null ?
                new ObjectParameter("ClaveAnterior", claveAnterior) :
                new ObjectParameter("ClaveAnterior", typeof(string));
    
            var claveNuevaParameter = claveNueva != null ?
                new ObjectParameter("ClaveNueva", claveNueva) :
                new ObjectParameter("ClaveNueva", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CambiarClaveUsuario", id_UsuarioParameter, claveAnteriorParameter, claveNuevaParameter);
        }
    }
}
