//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Gestión.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ListaClientes
    {
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string Empresa { get; set; }
        public string Proyecto { get; set; }
        public string RNC { get; set; }
        public string Cedula { get; set; }
        public string Primer_Nombre { get; set; }
        public string Segundo_Nombre { get; set; }
        public string Primer_Apellido { get; set; }
        public string Segundo_Apellido { get; set; }
        public string Tipo_Cliente { get; set; }
        public string Tel_Principal { get; set; }
        public Nullable<int> Extensión { get; set; }
        public string Tel_Secundario { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public string Punto_Referencia { get; set; }
        public string Ciudad { get; set; }
        public string Codigo_Postal { get; set; }
        public string Correo { get; set; }
        public string Web { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public Nullable<System.DateTime> Codigo_Fecha { get; set; }
        public string Observación { get; set; }
    }
}
