//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Gestión.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ListarEmpleados
    {
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string Primer_Nombre { get; set; }
        public string Segundo_Nombre { get; set; }
        public string Primer_Apellido { get; set; }
        public string Segundo_Apellido { get; set; }
        public string Cedula { get; set; }
        public string Telefono_Residencial { get; set; }
        public string Telefono_Celular { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public int Edad { get; set; }
        public string Correo { get; set; }
        public string Calle { get; set; }
        public int Numero { get; set; }
        public int Casa { get; set; }
        public string Sector { get; set; }
        public string Ciudad { get; set; }
        public string Nombre_Contacto_Emergencia { get; set; }
        public string Telefono_Contacto { get; set; }
        public string Genero { get; set; }
        public string Tipo_Sangre { get; set; }
        public string Puesto { get; set; }
        public string Departamento { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
        public string Supervisor { get; set; }
        public string Estatus { get; set; }
        public string Motivo_Estatus { get; set; }
        public string Condicion_Medica { get; set; }
        public string Seguro_Medico { get; set; }
        public Nullable<int> Categoria { get; set; }
        public System.DateTime Fecha_Emision_Licencia { get; set; }
        public System.DateTime Fecha_Expiracion_Licencia { get; set; }
        public string Seguro_Vehicular { get; set; }
        public Nullable<System.DateTime> Fecha_Expiracion_Seguro { get; set; }
        public byte[] Foto { get; set; }
        public string Observación { get; set; }
    }
}
