//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Gestión.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ListaProveedores
    {
        public string Nom_Proveedor { get; set; }
        public int id_Proveedor { get; set; }
        public string Rnc_Proveedor { get; set; }
        public string Contacto_Proveedor { get; set; }
        public int Comision_Definida { get; set; }
        public string Des_Proveedor { get; set; }
    }
}
