//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Gestión.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_VerFacturas
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public int NumFactura { get; set; }
        public string TipoFactura { get; set; }
        public string NCF { get; set; }
        public string Empresa { get; set; }
        public string RNC { get; set; }
        public string Contacto { get; set; }
        public string Telefonos { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string EstatusFactura { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> TotalFactura { get; set; }
        public Nullable<double> MontoPagado { get; set; }
        public Nullable<double> MontoPendiente { get; set; }
        public string MetodoPago { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> ITBIS { get; set; }
        public Nullable<System.TimeSpan> HoraFactura { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string Nota { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> VigenciaNCF { get; set; }
    }
}
