//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Gestión.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_VerComprobantesFiscales
    {
        public int id_Comprobante { get; set; }
        public int Comprobante_Desde { get; set; }
        public int Comprobante_Hasta { get; set; }
        public int Cantidad_Comprobantes { get; set; }
        public Nullable<int> Cantidad_Comprobantes_Usados { get; set; }
        public Nullable<int> Cantidad_Comprobantes_Disponibles { get; set; }
        public string Proximo_Comprobante { get; set; }
        public System.DateTime Fecha_Vencimiento_Comprobante { get; set; }
        public string Estatus_Comprobante { get; set; }
        public string Serie { get; set; }
        public string Tipo { get; set; }
    }
}
