//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Gestión.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_VerUsuarios
    {
        public int ID { get; set; }
        public string Usuario { get; set; }
        public string Perfil { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> UltimoAcceso { get; set; }
        public int Estatus { get; set; }
    }
}
